sudo: false

language: php

php:
    - 7.0
    - 5.2

env:
    - WP_VERSION=latest DEV_LIB_PATH=node_modules/wp-dev-lib

install:
    - nvm install node
    - npm install
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
