dist: xenial

language:
  - php
  - node_js

php:
  - "7.3"
  - "7.2"
  - "5.6"

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run mess -- -- --ignore-violations-on-exit

after_script:
  - npm run coverage

branches:
  only:
  - master
  - develop

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
