dist: trusty

sudo: false

language: php

php:
  - 7.0
  - 5.4

env:
  - WP_VERSION=latest DEV_LIB_PATH=node_modules/wp-dev-lib WP_ORG_SLUG=widget-context

install:
  - nvm install node
  - npm install
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

deploy:
  - provider: script
    script: scripts/deploy.sh $TRAVIS_TAG
    on:
      php: 7.0
      tags: true
  - provider: script
    script: scripts/deploy.sh trunk
    on:
      php: 7.0
      branch: master
