name: Lint and Test

on: push

jobs:

  test:
    name: Test and Lint
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        php-versions:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install tooling
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: composer test

      - name: Check mess
        run: npm run mess -- -- --ignore-violations-on-exit

      - name: Build
        run: npm run build

      - name: Zip
        run: ( cd dist && zip -q -r ../widget-context.zip . )

      - name: Upload ZIP
        uses: actions/upload-artifact@v7
        with:
          name: widget-context
          path: widget-context.zip

      - name: Attach to release
        if: startsWith( github.ref, 'refs/tags/' )
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cp widget-context.zip "widget-context.${{ github.ref_name }}.zip"
          gh release upload ${{ github.ref_name }} "widget-context.${{ github.ref_name }}.zip" --clobber

  release:
    name: Release to WordPress.org
    runs-on: ubuntu-24.04
    needs: test
    if: startsWith( github.ref, 'refs/tags/' )
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download ZIP
        uses: actions/download-artifact@v8
        with:
          name: widget-context
          path: .

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install --yes subversion rsync unzip zip

      - name: Unzip release
        run: unzip widget-context.zip -d widget-context

      - name: SVN clone
        run: svn checkout https://plugins.svn.wordpress.org/widget-context/ svn

      - name: Commit Blueprint Assets
        working-directory: svn
        run: |
          rsync --archive ../assets/blueprints/ assets/blueprints/
          svn add assets --force
          svn commit assets -m "Update blueprint assets for ${{ github.ref_name }}" --username "${{ secrets.WPORG_USERNAME }}" --password "${{ secrets.WPORG_PASSWORD }}" --non-interactive --no-auth-cache

      - name: Add to trunk and tag
        working-directory: svn
        run: |
          rsync --archive --delete --exclude=.svn ../widget-context/ trunk/
          svn add trunk --force
          svn cp trunk "tags/${{ github.ref_name }}"
          svn status

      - name: Commit Tag
        working-directory: svn
        run: svn commit "tags/${{ github.ref_name }}" -m "Release ${{ github.ref_name }}" --username "${{ secrets.WPORG_USERNAME }}" --password "${{ secrets.WPORG_PASSWORD }}" --non-interactive --no-auth-cache

      - name: Commit Stable Trunk
        if: ! contains( github.ref_name, '-' )
        working-directory: svn
        run: svn commit trunk -m "Release ${{ github.ref_name }}" --username "${{ secrets.WPORG_USERNAME }}" --password "${{ secrets.WPORG_PASSWORD }}" --non-interactive --no-auth-cache
